
name: Run ETL Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run ETL script
      run: python main.py

    - name: Upload charts.xlsx
      uses: actions/upload-artifact@v4
      with:
        name: charts
        path: output/charts.xlsx

    - name: Upload top_clients.xlsx
      uses: actions/upload-artifact@v4
      with:
        name: top_clients
        path: output/top_clients.xlsx
        
    - name: Upload aggregated data
      uses: actions/upload-artifact@v4
      with:
        name: agg_data
        path: output/agg_data.xlsx

    - name: Upload SQLite DB
      uses: actions/upload-artifact@v4
      with:
        name: agg_result_db
        path: output/agg_result.db
